name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}

      - name: Pull latest branch ${{ github.base_ref }}
        run: git pull ${{ github.base_ref }}

      - name: Test ${{ github.run_id }}
        run: ./gradlew build -x bootjar
