name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [8]
    steps:
      - uses: actions/checkout@v2

      - name: Verify signed gradle-wrapper.jar
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}
          
      - name: Test ${{ github.run_id }}
        run: ./gradlew build -x bootjar
