name: PR

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk-version}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version}}

      - name: Build with Gradle
        run: ./gradlew build -x bootjar
